### ISSUE TITLE
Initial GUI state?

### ISSUE THREAD

**Issue by smschwartz** [mucsci-students/2022fa-420-Velcro#95]
When I opened the GUI, the Class button was in the Remove state, so I couldn't figure out how to add an initial class to start to build a diagram... 
<img width="351" alt="Screen Shot 2022-11-02 at 1 02 06 PM" src="https://user-images.githubusercontent.com/17768351/199554519-60b95c7f-3cee-4142-a88c-c6b1c80b6769.png">

**Comment by smschwartz** [comment]
I did discover that I could click in the display window to add a class, but this was not obvious when faced with a blank window

**Comment by gps137** [comment]
Resolved in #117; added instructions on first GUI load.
